/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './../routes/__root';
import { Route as IndexImport } from './../routes/index';
import { Route as authSignupImport } from './../routes/(auth)/signup';
import { Route as authLoginImport } from './../routes/(auth)/login';
import { Route as appSettingsImport } from './../routes/(app)/settings';
import { Route as appProfileImport } from './../routes/(app)/profile';
import { Route as appAppImport } from './../routes/(app)/app';

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const authSignupRoute = authSignupImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any);

const authLoginRoute = authLoginImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any);

const appSettingsRoute = appSettingsImport.update({
  id: '/(app)/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any);

const appProfileRoute = appProfileImport.update({
  id: '/(app)/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any);

const appAppRoute = appAppImport.update({
  id: '/(app)/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/(app)/app': {
      id: '/(app)/app';
      path: '/app';
      fullPath: '/app';
      preLoaderRoute: typeof appAppImport;
      parentRoute: typeof rootRoute;
    };
    '/(app)/profile': {
      id: '/(app)/profile';
      path: '/profile';
      fullPath: '/profile';
      preLoaderRoute: typeof appProfileImport;
      parentRoute: typeof rootRoute;
    };
    '/(app)/settings': {
      id: '/(app)/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof appSettingsImport;
      parentRoute: typeof rootRoute;
    };
    '/(auth)/login': {
      id: '/(auth)/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof authLoginImport;
      parentRoute: typeof rootRoute;
    };
    '/(auth)/signup': {
      id: '/(auth)/signup';
      path: '/signup';
      fullPath: '/signup';
      preLoaderRoute: typeof authSignupImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/app': typeof appAppRoute;
  '/profile': typeof appProfileRoute;
  '/settings': typeof appSettingsRoute;
  '/login': typeof authLoginRoute;
  '/signup': typeof authSignupRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/app': typeof appAppRoute;
  '/profile': typeof appProfileRoute;
  '/settings': typeof appSettingsRoute;
  '/login': typeof authLoginRoute;
  '/signup': typeof authSignupRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/(app)/app': typeof appAppRoute;
  '/(app)/profile': typeof appProfileRoute;
  '/(app)/settings': typeof appSettingsRoute;
  '/(auth)/login': typeof authLoginRoute;
  '/(auth)/signup': typeof authSignupRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/app' | '/profile' | '/settings' | '/login' | '/signup';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/app' | '/profile' | '/settings' | '/login' | '/signup';
  id: '__root__' | '/' | '/(app)/app' | '/(app)/profile' | '/(app)/settings' | '/(auth)/login' | '/(auth)/signup';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  appAppRoute: typeof appAppRoute;
  appProfileRoute: typeof appProfileRoute;
  appSettingsRoute: typeof appSettingsRoute;
  authLoginRoute: typeof authLoginRoute;
  authSignupRoute: typeof authSignupRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appAppRoute: appAppRoute,
  appProfileRoute: appProfileRoute,
  appSettingsRoute: appSettingsRoute,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(app)/app",
        "/(app)/profile",
        "/(app)/settings",
        "/(auth)/login",
        "/(auth)/signup"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(app)/app": {
      "filePath": "(app)/app.tsx"
    },
    "/(app)/profile": {
      "filePath": "(app)/profile.tsx"
    },
    "/(app)/settings": {
      "filePath": "(app)/settings.tsx"
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx"
    },
    "/(auth)/signup": {
      "filePath": "(auth)/signup.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
