// This file is generated by npm run build:icons

export type IconName =
  | 'check'
  | 'chevron-down'
  | 'chevron-right'
  | 'chevron-up'
  | 'circle'
  | 'close'
  | 'menu'
  | 'search'
  | 'trash'
  | 'triangle-alert'
  | 'user';
